### ISSUE TITLE
Cursor color

### ISSUE THREAD

**Issue by andrepolischuk** [andrepolischuk/hyperterm-one-light#6]
@iamstarkov what do you think about making cursor color like in atom?

![screen shot 2016-08-15 at 15 05 43](https://cloud.githubusercontent.com/assets/8956796/17664193/079790ee-62fb-11e6-874c-fa35911f1a86.png)

**Comment by iamstarkov** [comment]
well, i dont have the same cursor in atom
![screen shot 2016-08-16 at 02 01 24](https://cloud.githubusercontent.com/assets/559321/17683673/5f572c0e-6355-11e6-81aa-1ff0d639a5ee.png)

**Comment by andrepolischuk** [comment]
Cursor is block in HyperTerm by default on my screenshot. You dont have the same cursor in atom because you are in selection mode. In normal mode cursor looks like this: 

![image](https://cloud.githubusercontent.com/assets/8956796/17694405/5ec8bc06-63ac-11e6-95ee-9e1a9bc5e82a.png)

Color is the same as in atom.

**Comment by iamstarkov** [comment]
you are right, lets do that

**Comment by iamstarkov** [comment]
lets also fix crappy cursor node while `
![screen shot 2016-08-16 at 16 05 00](https://cloud.githubusercontent.com/assets/559321/17701736/3f7c2fc6-63cb-11e6-9984-30698b7264b7.png)
focus=false`

**Comment by andrepolischuk** [comment]
> lets also fix crappy cursor node while focus=false

You mean that cursor must be identical if `focus` is `true` and `false`?

**Comment by iamstarkov** [comment]
yeah

**Comment by andrepolischuk** [comment]
Cursor is hidden while `focus = false` in atom

**Comment by iamstarkov** [comment]
lets do the same, or is it a bad idea in some cases?

**Comment by andrepolischuk** [comment]
I can't remember such cases now

**Comment by iamstarkov** [comment]
then, lets fix it and call it a day

**Comment by iamstarkov** [comment]
do you want me to make a pr, or you want to do that on your own?

**Comment by andrepolischuk** [comment]
I'll do

**Comment by andrepolischuk** [comment]
#7

**Comment by andrepolischuk** [comment]
Closed via #7
