### ISSUE TITLE
split panes support

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/hyperterm-one-light#8]

**Comment by andrepolischuk** [comment]
Is ok?

![screen shot 2016-10-07 at 13 34 38](https://cloud.githubusercontent.com/assets/8956796/19187210/d196e096-8c92-11e6-8dd8-3090a9fb03ee.png)

**Comment by iamstarkov** [comment]
yep

**Comment by iamstarkov** [comment]
have you updated to 0.8.1?

**Comment by andrepolischuk** [comment]
Yes, i fixed some bugs for 0.8.1

**Comment by iamstarkov** [comment]
cool

**Comment by iamstarkov** [comment]
your branch looks good

**Comment by iamstarkov** [comment]
i thinks good plan for future release is:
* [ ] merge this
* [ ] publish new version
* [ ] deprecate it
* [ ] rename
* [ ] publish with new name

what do you think?

**Comment by iamstarkov** [comment]
@andrepolischuk piu
